CREATE TABLE IF NOT EXISTS rag_request_telemetry (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id TEXT UNIQUE,
  created_at TIMESTAMPTZ,
  timestamp TIMESTAMPTZ,
  repo_name TEXT,
  mode TEXT,
  user_query TEXT,
  model_name TEXT,
  embedding_model TEXT,
  top_k INTEGER,
  rerank_enabled BOOLEAN,
  final_answer_length INTEGER,
  status TEXT,
  stage_failed TEXT,
  error_message TEXT,
  total_latency_ms DOUBLE PRECISION,
  embedding_latency_ms DOUBLE PRECISION,
  pinecone_query_latency_ms DOUBLE PRECISION,
  rerank_latency_ms DOUBLE PRECISION,
  llm_latency_ms DOUBLE PRECISION,
  postprocess_latency_ms DOUBLE PRECISION,
  time_to_first_retrieval_ms DOUBLE PRECISION,
  time_to_final_answer_ms DOUBLE PRECISION,
  pinecone_read_units DOUBLE PRECISION,
  pinecone_write_units DOUBLE PRECISION,
  pinecone_query_count INTEGER,
  pinecone_cost_usd_est DOUBLE PRECISION,
  llm_input_tokens INTEGER,
  llm_output_tokens INTEGER,
  llm_cached_input_tokens INTEGER,
  llm_cost_usd_est DOUBLE PRECISION,
  embedding_input_tokens INTEGER,
  embedding_cost_usd_est DOUBLE PRECISION,
  rerank_input_tokens INTEGER,
  rerank_cost_usd_est DOUBLE PRECISION,
  total_cost_usd_est DOUBLE PRECISION,
  retrieved_file_count INTEGER,
  retrieved_chunk_count INTEGER,
  selected_chunk_count INTEGER
);

CREATE INDEX IF NOT EXISTS idx_rag_request_telemetry_created_at
  ON rag_request_telemetry(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_rag_request_telemetry_mode
  ON rag_request_telemetry(mode);

CREATE INDEX IF NOT EXISTS idx_rag_request_telemetry_repo
  ON rag_request_telemetry(repo_name);
